### PR TITLE
Improved Readme.md . Changes aim to improve the formatting, clarify steps, and ensure consistency throughout your README

### PR DESCRIPTION
**Pull request by vinayaksoni1729**

### CODE REVIEW

**Comment by hlohaus** [comment]
Your PR add only a space?

**Comment by vinayaksoni1729** [comment]
@hlohaus  not actually added how to add cookies manually

**Comment by hlohaus** [comment]
There a already a "cookies" part from me

**Comment by vinayaksoni1729** [comment]
@hlohaus that is true but no instruction about how to add it manually if not on localhost

**Pull request closed without merging**
