### PR TITLE
Fix: Model sometimes not converted

### PR DESCRIPTION
**Pull request by nullstreak**
Model is not converted properly, when model is `string` and provider is `ProviderType`.

Maybe needs some additional testing 🤔

### CODE REVIEW

**Comment by hlohaus** [comment]
The model should not be converted in this case. We can pass the input directly to the providers.

**Comment by nullstreak** [comment]
@hlohaus 

```
g4f.ChatCompletion.create(
    messages=[{'role':'user', 'content': 'test'}], 
    model='dolphin-mixtral-8x7b',
    provider=g4f.Provider.DeepInfra,
    stream=True,
)
```
Produces error:
```
Traceback (most recent call last):
  File "/home/vlad/Documents/Apps/gpt4free/./generate.py", line 161, in <module>
    main()
  File "/home/vlad/Documents/Apps/gpt4free/./generate.py", line 155, in main
    for message in response:
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 142, in create_completion
    yield loop.run_until_complete(gen.__anext__())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/Provider/DeepInfra.py", line 58, in create_async_generator
    response.raise_for_status()
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/g4f/requests.py", line 25, in raise_for_status
    self.inner.raise_for_status()
  File "/home/vlad/Documents/Apps/gpt4free/venv/lib/python3.11/site-packages/curl_cffi/requests/models.py", line 80, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 404: Not Found
```

Because it doesn't convert "dolphin-mixtral-8x7b" to "cognitivecomputations/dolphin-2.6-mixtral-8x7b".


While this runs successfully:
```
g4f.ChatCompletion.create(
    messages=[{'role':'user', 'content': 'test'}], 
    model='dolphin-mixtral-8x7b',
    provider=None,
    stream=True,
)
```

Even thought it's technically the same provider.

**Comment by hlohaus** [comment]
Oh i see the problem. Maybe we can make the convertion only if possible. And don't raise a exception.

**Comment by hlohaus** [comment]
I created tests and fixed the issue in all cases: #1508

**Pull request closed without merging**
