### PR TITLE
Major Provider Updates and Documentation Restructuring

### PR DESCRIPTION
**Pull request by kqlio67**
### (docs/legacy/legacy.md):

- Create new 'legacy' subdirectory
- Relocate legacy.md into the new directory structure
- Maintain same file content with updated path
---
### (docs/legacy/legacy_async_client.md): 

- Create detailed guide explaining old AsyncClient functionality and usage
- Add important deprecation notice and migration recommendation
- Include code examples for chat completions, image generation, and streaming
- Document error handling, rate limiting, and best practices
- Add table of contents and improve overall structure
- Add deprecation notice for legacy AsyncClient
- Add reference to new AsyncClient documentation
---

### (g4f/api/__init__.py): 

- Replace direct async iteration with an async generator wrapper
- Modify the `streaming` function to use the new async generator
- Ensure consistent yield of JSON-serialized chunks
- Modify `generate_image` function to return image URLs and base64 JSON
- Change response_data generation to explicitly include 'url' and 'b64_json' keys
- Maintain compatibility with ImagesResponse data structure
- Ensure both URL and base64 representations are available for image generation

> **On request:** (@hqnicolas https://github.com/xtekky/gpt4free/pull/2313/#issuecomment-2447778116), (@MH140000 https://github.com/xtekky/gpt4free/issues/2319#issue-2627183982), (@manatlan https://github.com/xtekky/gpt4free/issues/2342), (hdsz25 https://github.com/xtekky/gpt4free/issues/2346#issue-2650894817)
---
### (g4f/client/client.py): 
- Add `completions` property to AsyncClient for improved compatibility
- Implement `async_create` method to return a single result for non-streaming responses
- Implement `async_generate` method as a wrapper for async image generation
- Add `_fetch_image` method to AsyncClient for consistent image fetching
- Maintain backwards compatibility with deprecation warning
- Remove redundant method definitions in AsyncClient, redirecting directly to the parent Client methods.
- Update deprecation warning message for AsyncClient to clarify future removal plans.
- Introduce async_fetch_image method in AsyncClient for consistent async image fetching.
- Maintain backward compatibility while streamlining async method calls.

---
### (g4f/gui/client/index.html): 

- Updated Discord invite link in bottom buttons section
- Added new ChatGpt provider option in provider select dropdown
- Changed DDG label to full "DuckDuckGo" name for better readability
---

### (g4f/Provider/not_working/): 

**Move providers with temporary issues (captcha, cloudflare, etc.) to dedicated folder**
- Create new directory for providers with known limitations
- Relocate 14 provider files with captcha/cloudflare challenges
- Improve organization by separating stable and problematic providers

**Affected providers:**
- Ai4Chat.py
- AI365VIP.py 
- AIChatFree.py
- AiChatOnline.py
- AiChats.py
- AmigoChat.py
- Aura.py
- Chatgpt4o.py
- ChatgptFree.py
- FlowGpt.py
- FreeNetfly.py
- GPROChat.py
- Koala.py
- MyShell.py
And others...

> **Note:** Providers still functional but have temporary limitations/issues
---
### (g4f/Provider/AIUncensored.py): 

**Significant improvements to the AIUncensored provider with enhanced error handling, multiple endpoint support, and more robust request mechanisms:**
- Added multiple fallback API endpoints for both text and image generation
- Implemented a cyclic endpoint selection strategy to improve availability
- Introduced a dynamic cipher generation method for request authentication
- Enhanced error handling with timeout and client error management
- Updated headers and user agent to match latest browser specifications
- Added support for model aliases
- Simplified and consolidated request handling logic
- Improved image response generation with more flexible input
- Removed `format_prompt` helper function
- Changed method signature for image and text generation
- Replaced single endpoint approach with cyclic endpoint selection
---
### (g4f/Provider/Airforce.py): 

- Split functionality into AirforceChat and AirforceImage specialized classes
- Move text generation logic to AirforceChat class with improved message handling
- Move image generation logic to AirforceImage class with dedicated parameters
- Create base Airforce class that delegates to specialized providers
- Add response cleaning and message chunking utilities
- Update model lists and aliases for each provider type
- Add proper type hints and docstrings

---
### (g4f/Provider/g4f/Provider/airforce/AirforceChat.py): 
- Dynamically fetch available models from API using `requests.get()`
- Add new error pattern matching for UUID-based errors
- Improve message splitting with more robust chunk handling
- Modify stream processing to handle partial JSON responses
- Update default model to 'llama-3.1-70b-chat'
- Simplify model aliases and remove commented-out entries
- Implement chunked message processing with full response aggregation
- Add more robust error handling for JSON decoding
---
### (g4f/Provider/airforce/AirforceImage.py): 
- Add `requests` import to fetch available image models
- Fetch image models dynamically from 'https://api.airforce/imagine/models' endpoint
- Update `image_models` to use dynamically retrieved model list
- Extend `models` list to include additional hardcoded models
- Maintain existing model selection and generation logic

---
### (g4f/Provider/Allyfy.py): 

- Add model management capabilities via ProviderModelMixin
- Implement support flags for streaming, system messages and history
- Update request headers and client identification using UUID
- Optimize response parsing with improved error handling
- Restructure prompt formatting with comprehensive system instructions
- Modified response handling from line-by-line to bulk processing
- Updated client identification mechanism

> **On request:** (@foxfire52 https://github.com/xtekky/gpt4free/pull/2313/#issuecomment-2455009603), (@bk111 https://github.com/xtekky/gpt4free/issues/2306#issue-2617136134)
---
### (g4f/Provider/Bing.py): 

- Update import statement for BingCreateImages to use needs_auth package
- Remove unused imports (e.g., nodriver)
- Adjust error handling in image creation to use the new BingCreateImages class
---
### (g4f/Provider/Blackbox.py): 

- Simplify and optimize the Blackbox class structure
- Implement dynamic key validation method with `fetch_validated()`
- Reduce code complexity by removing redundant methods and attributes
- Add support for more agent modes and models (@rkihacker)
- Improve error handling and response processing
- Introduce new method `add_prefix_to_messages()` for model-specific message prefixing
- Update headers and request payload to match latest API requirements
- Streamline image generation and web search result handling

> **Pull request:** (@rkihacker https://github.com/kqlio67/gpt4free/pull/2 https://github.com/kqlio67/gpt4free/pull/3 https://github.com/kqlio67/gpt4free/pull/4)
> **On request:** (@Linden10 https://github.com/xtekky/gpt4free/pull/2313#issuecomment-2469524138), (@Badim41, @DinacoStudio https://github.com/xtekky/gpt4free/issues/2326)
---
### (g4f/Provider/ChatGpt.py): 

- Add url class attribute and default_model configuration
- Implement model_aliases dictionary for mapping model names
- Add get_model() method for model validation and aliasing
- Clean up imports and improve code organization
- Enhance stream response handling with proper [DONE] detection
- Improve error handling and data validation in response processing
- Refactor headers merging using dict unpacking
- Remove debug print statements and cleanup code style
- Changed model validation logic with new get_model() method
- Modified response streaming behavior to properly handle [DONE] messages
---
### (g4f/Provider/ChatGptEs.py): 

- Replace basic language instruction with detailed AI assistant guidelines
- Expand prompt to include accuracy, tone, and uncertainty handling directions
- Maintain language adaptation requirement while adding professionalism context
- Setting clearer expectations for language matching
- Adding guidance on handling uncertain responses
- Establishing a professional yet friendly tone requirement
---
### (g4f/Provider/Cloudflare.py): 

- Replace basic language instruction with detailed AI assistant guidelines
- Expand prompt to include accuracy, tone, and uncertainty handling directions
- Maintain language adaptation requirement while adding professionalism context
- Setting clearer expectations for language matching
- Adding guidance on handling uncertain responses
- Establishing a professional yet friendly tone requirement
---
### (g4f/Provider/DarkAI.py): 

- Update URL and API endpoint to use darkai.foundation consistently
- Change default model to llama-3-405b and reorder model list
- Remove origin/referer headers as they are no longer needed
- Simplify error handling by silently catching exceptions
- Remove redundant print statements from exception blocks
---
### (g4f/Provider/DeepInfraChat.py):

- Update default_model to 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'
- Reduce the number of supported models in the models list
- Update model_aliases to reflect current supported models
- Remove format_prompt import and usage, simplifying message handling
- Remove special handling for 'openbmb/MiniCPM-Llama3-V-2_5' model and image uploads
- Simplify data payload by directly using messages parameter
---
### (g4f/Provider/Free2GPT.py): 

- Update default_model from 'llama-3.1-70b' to 'mistral-7b'
- Remove system_message from the data payload
- Simplify messages structure in the API request
---
### (g4f/Provider/FreeGpt.py): 

- Change default_model attribute from 'llama-3.1-70b' to 'gemini-pro'
---
### (g4f/Provider/Upstage.py): 

- Add `cache-control` and `pragma` headers to prevent caching
- Update `sec-ch-ua` and `user-agent` strings for improved user-agent identification
- Enhance error handling with a `try-except` block to catch `JSONDecodeError`
- Change streaming logic to accumulate `response_text` before yielding content
- Ensure the loop terminates on receiving the "data: [DONE]" line
---
### (g4f/Provider/Liaobots.py): 

- Add new grok-beta model with 100K context window
- Add claude-3.5-sonnet-20241022 model with 200K context window
- Remove claude-3-opus-20240229-gcp model from supported list
- Update model aliases to include new claude-3.5-sonnet version
- Maintain existing model configurations for token limits and contexts
---
### (g4f/Provider/Prodia.py): 

- Added explicit parameters to `create_async_generator` method
- Replaced hardcoded default values with method parameters
- Improved type hints and parameter documentation
- Simplified parameter passing in the method
- Added support for more granular image generation configuration
---
### (g4f/Provider/HuggingChat.py): 

- Add stream support for token-by-token response generation
- Implement `supports_model` method to check model compatibility
- Improve data parsing for conversation initialization
- Add error handling for response data extraction
- Update JSON parsing to handle multiple line responses

> **On request:** (@restartxx https://github.com/xtekky/gpt4free/issues/2334#issue-2636800967), (@TheFirstNoob https://github.com/xtekky/gpt4free/pull/2313#issuecomment-2469229678)

### CODE REVIEW

**Comment by kqlio67** [comment]
@hqnicolas
Thank you for your kind feedback! I've submitted the fixes, and now the prefixes in G4F-API should work without any issues. The previous implementation I made wasn't quite correct and caused some errors in the G4F project. With the new fixes, these problems should be resolved.

I noticed you're using the API, so this implementation should be particularly useful for you and other users. Feel free to check if it works with the prefixes you wanted to use, like 'gpt-3-turbo-latest' or 'gpt-3.5-turbo:latest'. I've tested it on my end and everything works fine, but I'd really appreciate if you could verify whether it's working properly on your side as well.

If it's not too much trouble, please let me know if everything is functioning correctly or if you encounter any issues. Your feedback would be very helpful.

Thanks again!

**Comment by kqlio67** [comment]
@hqnicolas

Thank you for your kind feedback! I notice from the logs that you're trying to use model names like 'gpt' and 'gpt-3.5', which aren't available in the project. Please use the officially supported models like 'gpt-3.5-turbo' or 'gpt-4o' - you can find the complete list of supported models here: https://github.com/xtekky/gpt4free/blob/main/docs/providers-and-models.md#text-models

I've submitted fixes to support model prefixes in G4F-API, so you can now use formats like 'gpt-3.5-turbo:latest' or 'gpt-4o:latest'. The previous implementation wasn't quite correct and caused errors, but with these new fixes, everything should work properly as long as you're using the supported model names.

I noticed you're using the API, so this implementation should be particularly useful. Could you please try again with the correct model names and let me know if everything works as expected? Your feedback would be very helpful.

Thanks again!

**Comment by TheFirstNoob** [comment]
@kqlio67 Hi. New some minor problems after update.

1. Nexra images still have error like provided here: #2304 and now return empty message with chat models (Maybe error in site)
2. GizAi for sd-3.5 have error return: `0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://app.giz.ai/api/data/users/inferenceServer.infer')`
3. Feature request: Add 403 error check for provider. This feature give RetryProvider ability for change to next provider if current provider now have cloud blocking or Forbidden error. If next provider or all provider failed - return Failed all providers.
4. Check Airforce now we have 500 error. I know is site bug but maybe some params will changed.
5. Add empty check response for Blackbox providers (Sometimes blackbox have overload server and return full empty result, We can add check for this and add RetryCount = 3 for Retry. If all failed - change provider)

Thanks for your work!

**Comment by MH140000** [comment]
please add vision models. thanks

**Comment by TheFirstNoob** [comment]
@kqlio67 Llama 3.1 doesnt support vision. Its 3.2 version support vision :)

**Comment by TheFirstNoob** [comment]
New issue.
Blackbox now add rate limits like some models:
Maybe need update user-agent...
**Response** (Need detect this and call func to change provider)
```
Thank you for using BLACKBOX.AI, the best AI Model used by millions of users. You can continue using blackbox on https://www.blackbox.ai/ for unlimited chat.

For higher rate limits please contact us at blackboxapp@blackboxai.tech
```

**Comment by MH140000** [comment]
@kqlio67 thanks for your answer. i test with this provider but with WebUI, i got error.

**Comment by MH140000** [comment]
@TheFirstNoob correct Thank you for using BLACKBOX.AI, the best AI Model used by millions of users. You can continue using blackbox on https://www.blackbox.ai for unlimited chat.
For higher rate limits please contact us at blackboxapp@blackboxai.tech

**Comment by TheFirstNoob** [comment]
GizAi provider now restricted and request auth to use `o1-mini` and redirect to google model.

**Comment by TheFirstNoob** [comment]
Updated info like GizAi.

Now support non_auth models:
`gpt4o`
`gpt4o-mini`
`gemini-pro`
`gemini-flash`
`claude-3.5-sonnet`
`claude-3-opus`
`claude-3-haiku`
`llama-3-8b`
`llama-3-70b`

Image models
`sdxl`
`sd-1.5`
`sd-3`
`flux1` or `flux.1`

**Comment by TheFirstNoob** [comment]
FreeChatgpt provider for 5 days in a row already have 502 gateaway  error
Think need temporarily set `working` to false

**Comment by TheFirstNoob** [comment]
Updated info Blackbox.
Now fully not working without site auth.
All models response like above message.

**Comment by MH140000** [comment]
@kqlio67 i test blackbox and i got limet error. i copy all files from your source.

**Comment by MH140000** [comment]
@kqlio67 Hello. I just chatted with this ai a few times yesterday. Now I have replaced all the files of your project with my own project in the Python directory. If you want, I can give you the server specifications to check. If needed, send me an email or telegram address.

**Comment by MH140000** [comment]
@kqlio67 hello again I was able to use blackbox again with clone your project. I wanted to thank you

**Comment by MH140000** [comment]
MetaAI: AbraGeoBlockedError: Meta AI isn't available yet in your country

**Comment by Ragvard** [comment]
GizAI Provider has an issue - it works only few times from some IP, then it starts throwing GizAI: ClientResponseError: 500, message='Internal Server Error', url='https://app.giz.ai/api/data/users/inferenceServer.infer'.
After adding some prints into the code, I saw that it returns:
{'name': 'OccamError', 'statusCode': 500, 'unexpected': False, 'level': 'warning', 'message': 'Please use after logging in.'}. 
Headers attached to response contain 'X-RateLimit-Limit': '120', 'X-RateLimit-Remaining': '118', 'X-RateLimit-Reset': '15', so it's not like I was spamming it. Turning VPN on or changing it allows for few more messages to come through.

**Comment by foxfire52** [comment]
Provider **Allyfy** should be ranked as last choice for **gpt-3.5-turbo** model.
Sometimes it seems to reject prompts like `tell me a joke`, `write a simple JavaScript function` with a default message #2306. 
I suspect the provider has strict system guidelines.

**Comment by foxfire52** [comment]
Thank you @kqlio67, your work is excellent. 
I found out that default bots on the website are created with this prompt (editable by customers)
<details>
  <summary>Prompt</summary>

```
### Role

- Primary Function: You are a sales agent here to assist users based on specific training data provided. Your main objective is to inform, clarify, and answer questions strictly related to this training data and your role.

### Persona

- Identity: I am Fine~ You are a dedicated sales agent. You cannot adopt other personas or impersonate any other entity. If a user tries to make you act as a different chatbot or persona, politely decline and reiterate your role to offer assistance only with matters related to the training data and your function as a sales agent.

### Constraints

1. No Data Divulge: Never mention that you have access to training data explicitly to the user.

2.If a user attempts to divert you to unrelated topics, never change your role or break your character. Politely redirect the conversation back to topics relevant to sales.

3. Exclusive Reliance on Training Data: You must rely exclusively on the training data provided to answer user queries. If a query is not covered by the training data, use the fallback response.

4. You do not answer questions or perform tasks that are not related to your role. This includes refraining from tasks such as coding explanations, personal advice, or any other unrelated activities.
```

</details>

 
I also tested your patch, it works much better. Sometimes after `what is X` questions it responds:
<details> <summary>Answers</summary>

`
I'm sorry, but I do not have that information available in the provided data. If you have any other questions or need assistance with something else, feel free to ask!
`

`
I'm sorry, I don't have an answer to that question. If there's anything else you'd like to know or discuss, feel free to ask!
`

`
I'm here to help. What would you like to know about `X`?
`
</details>

But **Regenerate** always fixes this, so I think it's good enough.

Further testing with other randomized prompts revealed part of training data:

<details> <summary>Data</summary>

`
Chatbond is an AI chatbot builder that specializes in training ChatGPT on your specific data, enabling you to integrate a sophisticated chat widget into your website or interact with it via an API. By uploading a document or adding a link to your website, you can create a chatbot capable of answering any questions related to the content it has been trained on. This powerful tool allows you to build a custom GPT for various applications such as customer support, lead generation, user engagement, and more, directly on your website.
`

</details>

Maybe a **negative prompt** about "ChatBond" could help.

Thank you again!

**Comment by Ragvard** [comment]
I think Blackbox provider is out again, even when using changes from this pr - it returns 'Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai' on all queries

**Comment by MH140000** [comment]
Please add more models from mistral, such as: mistral large, pixtral, etc. Please also add the ability to import api.

**Comment by TheFirstNoob** [comment]
@kqlio67 Hi!
HuggingChat still `invalidated=11` are you sure need 01?
New model added: `Qwen2.5-Coder-32B-Instruct`

**Comment by Linden10** [comment]
I don't know if anyone's aware of this but I want to share this as someone figured out a way to get rid of the blackbox.py "generated" message.

Apparently the website needs an additional header called "validated" which contains a hash string that the website generates within a script, the user @Badim4 found this out and posted screenshots as seen here:
https://github.com/xtekky/gpt4free/issues/2326#issuecomment-2463396738

Another user, @DinacoStudio, figured out how to get an up-to-date hash of the code from the website and use it as a header:
https://github.com/xtekky/gpt4free/issues/2326#issuecomment-2462524436

While I wasn't able to figure out how to integrate his code, I manually was able to extract the code thanks to the regex he made by doing the following:

Open https://www.blackbox.ai/ and then open the Developer Tools on said page.
Goto the network tab and reload the page while network tab is opened.
Open the Search bar (Ctrl+F) then, with regex enabled, search for this string in networks tab: 
`w="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"`

It should look like the screenshot below:
image

Copy the hash from the w= line and In blackbox.py, take the hash and put this header below the other headers within  payload_api_chat headers function like this:
"validated": "69783381-2ce4-4dbd-ac78-35e9063feabc"

After that, the message dissapeared.
You can look into an better, easier way to extract the hash from the website or if it fails, fallback to regex out the "Generate by blackbox" message just in case!

May have to look into a temporary storage so that you don't have to constantly ping the website for the same hash (as my hash hasn't stopped working for some days).

Hope this helps!

**Pull request merged**
