### PR TITLE
Add create images to Bing

### PR DESCRIPTION
**Pull request by hlohaus**

### CODE REVIEW

**Comment by iG8R** [comment]
Hi.
Could you please clarify how this Bing's image creation feature can be used via the g4f gui?

**Comment by CrhistopherDiaz** [comment]
Create images with prompt: un alienigena que diga asd
Open browser with config dir: C:\Users\Crhistopher\AppData\Local\g4f\g4f
Exception ignored in: <async_generator object stream_generate at 0x000001993D2C1240>
Traceback (most recent call last):
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\retry_provider.py", line 34, in create_completion
    yield token
RuntimeError: async generator ignored GeneratorExit
ERROR:root:HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\gui\server\backend.py", line 80, in try_response
    for chunk in ChatCompletion.create(
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\create_images.py", line 52, in create_completion
    yield from self.create_images(prompt)
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\bing\create_images.py", line 145, in create_completion
    driver = get_browser(proxy=proxy)
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\webdriver.py", line 35, in get_browser
    return Chrome(
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

 error

**Comment by hlohaus** [comment]
You ask the assistant for creating images. It responses with images from Bing Image Creator.

**Comment by CrhistopherDiaz** [comment]
Using Bing provider and gpt-4 model
Open browser with config dir: C:\Users\Crhistopher\AppData\Local\g4f\g4f

 de ahi no pasa se queda hay y no devuelve nada

**Comment by CrhistopherDiaz** [comment]
despues aroja Exception ignored in: <async_generator object stream_generate at 0x000001F38124DDC0>
Traceback (most recent call last):
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\create_images.py", line 52, in create_completion
    yield from self.create_images(prompt)
RuntimeError: async generator ignored GeneratorExit
ERROR:root:HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\gui\server\backend.py", line 80, in try_response
    for chunk in ChatCompletion.create(
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\create_images.py", line 52, in create_completion
    yield from self.create_images(prompt)
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\bing\create_images.py", line 145, in create_completion
    driver = get_browser(proxy=proxy)
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\webdriver.py", line 35, in get_browser
    return Chrome(
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
ChatAnywhere: ClientResponseError: 522, message='', url=URL('https://chatanywhere.cn/v1/chat/gpt/')
Using Bing provider
10.15.0.2 - - [04/Jan/2024 14:56:52] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:10.15.0.2 - - [04/Jan/2024 14:56:52] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Exception ignored in: <async_generator object stream_generate at 0x000001F38124DDC0>
Traceback (most recent call last):
  File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\retry_provider.py", line 34, in create_completion
    yield token
RuntimeError: async generator ignored GeneratorExit

**Comment by CrhistopherDiaz** [comment]
> You ask the assistant for creating images. It responses with images from Bing Image Creator.

como solucionar el error Create images with prompt: un alienigena que diga asd
Open browser with config dir: C:\Users\Crhistopher\AppData\Local\g4f\g4f
Exception ignored in: <async_generator object stream_generate at 0x000001993D2C1240>
Traceback (most recent call last):
File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\retry_provider.py", line 34, in create_completion
yield token
RuntimeError: async generator ignored GeneratorExit
ERROR:root:HTTP Error 403: Forbidden
Traceback (most recent call last):
File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\gui\server\backend.py", line 80, in try_response
for chunk in ChatCompletion.create(
File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\create_images.py", line 52, in create_completion
yield from self.create_images(prompt)
File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\Provider\bing\create_images.py", line 145, in create_completion
driver = get_browser(proxy=proxy)
File "C:\Users\Crhistopher\Downloads\Compressed\gpt4free-best - bing\gpt4free-best\g4f\webdriver.py", line 35, in get_browser
return Chrome(
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver_init_.py", line 258, in init
self.patcher.auto()
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
self.unzip_package(self.fetch_package())
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
return urlretrieve(download_url)[0]
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
response = meth(req, response)
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
response = self.parent.error(
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
return self._call_chain(*args)
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
result = func(*args)
File "C:\Users\Crhistopher\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by hlohaus** [comment]
The error are in undetected_chromedriver. You can't download the Chromedriver. Try out the docker install. It has his own Chromedriver.

**Comment by Mylinde** [comment]
@hlohaus

Is the with this commit provided code,  the necessary code to implement the feature in an g4f based project?

**Comment by hlohaus** [comment]
Yes, i have not now a example. But in GUI is a Button for Image Generation.

**Comment by Mylinde** [comment]
The button/buttons are already implemented. Know I need to implement the functions at the right place, also for file upload. Hope I can get around, because the code of the project ist a little bit different.

**Comment by Mylinde** [comment]
@hlohaus
Can you take a look over if you would contribute by implementing the features?

**Pull request merged**
