### PR TITLE
Add new provider, enhance functionality, and update docs

### PR DESCRIPTION
**Pull request by kqlio67**
## # New provider added
   - **g4f/Provider/GizAI.py**
      - **Text generation:** `gemini-flash, gemini-pro, gpt-4o-mini, gpt-4o, claude-3.5-sonnet, claude-3-haiku, llama-3.1-70b, llama-3.1-8b, mistral-large`
      - **Image generation:** `sdxl, sd-1.5, sd-3.5, flux-schnell`
---

## G4F update
**(docs/providers-and-models.md): add GizAI provider with multiple models**
   - Introduce a new AI provider, GizAI, with support for various text and image models. 
      - **Text Models:** gemini-flash, gemini-pro, gpt-4o-mini, gpt-4o, claude-3.5-sonnet,  claude-3-haiku, llama-3.1-70b, llama-3.1-8b, mistral-large
     - **Image Models:** sd-1.5, sd-3.5,  flux-schnell

> This addition provides users with more options for text generation  and image creation tasks.
> **BREAKING CHANGE:** GizAI provider includes new models and capabilities.
---
**(g4f/gui/server/api.py): enhance image handling and directory management**
   - Enhance image handling functionalities and ensure image directory exists
      - Add ensure_images_dir function to create image directory if it doesn't exist
      - Modify serve_images and _copy_images methods to use ensure_images_dir
      - Remove unnecessary imports to clean up code
      - Update typing annotations to improve type safety

> This ensures that the directory for storing images is always present and improves code readability and maintainability.
---
**(g4f/gui/server/website.py): add redirect for /images/ endpoint**
   - Add a new route '/images/' to the website routes configuration
      - The new route redirects to the home page similar to other routes
      - Supports both GET and POST methods

> This change ensures consistency in route management and better handles potential future expansion for the '/images/' endpoint.
---
**(g4f/gui/client/index.html): enhance model/provider options**
   - Enhanced model selection options by adding new models such as gpt-4o, gpt-4o-mini, llama-3.1-405b, mixtral-8x7b, gemini-flash, claude-3-haiku, and claude-3.5-sonnet.
   - Enhanced provider selection options by adding new providers such as DeepInfraChat, ReplicateHome, Blackbox, HuggingChat, DDG, and Pizzagpt.

> These changes improve the user interface by expanding the available options for models and providers.
---

## # G4F improvements
**(g4f/api/__init__.py): refactor API structure and improve async handling**
   - Updated `create_app` to accept an optional `g4f_api_key` parameter.
   - Refactored `ChatCompletionsForm` to `ChatCompletionsConfig` and `ImagesGenerateForm` to `ImageGenerationConfig`.
   - Improved async handling for `chat_completions` and `generate_image` endpoints.
   - Added type hints for better readability and maintainability.
   - Updated routes to include `/v1/images/generate`.
   - Enhanced error handling and logging.
   - Introduced global `list_ignored_providers` and related setter method.

> Breaking change: Some API endpoints and request/response formats have been modified.
> https://github.com/xtekky/gpt4free/issues/2222#issue-2521995710
---
**(g4f/models.py): add new provider GizAI and update best providers**
   Add GizAI as a new provider for various models and update best provider lists
      - Add GizAI to the imports and update best provider lists for several models
      - Update `default` model's best providers
      - Adjust `gpt-4o`, `gpt-4o-mini`, `gpt-4`, `o1-mini`, `llama-3.1-8b`, `llama-3.1-70b`, `mistral-large`, `claude-3-haiku`, `claude-3.5-sonnet`, `gemini-pro`, `gemini-flash`, `sd-1.5`, `sd-3.5`, and `flux-schnell` to include GizAI

> Breaking change: Best provider logic updated to include new provider
---

## # Updating documentation and improving G4F
**(README.md): update README with badges and links**
   - Add new badges for commits, issues, and license at the top for improved visibility
   - Enhance author attribution with centered formatting
   - Correct various internal links within the Table of Contents
   - Fix broken link to the Interference API documentation
   - Adjust formatting for better readability and consistency throughout the file
   
   - Correct typo in the "Latest version" note and update internal links
      - Fix "Lastet" to "Latest" in the version note section
      - Update "Installation Guide for Windows (.exe)" link in the What's New section
      - Update link formats for internal references and external URLs
---
**(docs/async_client.md): update guide compatibility and improved chat completions example**
   - Introduce new section for creating chat completions with an improved example
   - Update table of contents to include new section

> This update enhances the guide by providing clearer instructions for developers familiar with the OpenAI interfaces, making the transition to G4F smoother. The improved example helps developers understand how to create chat completions more effectively.
---
**(docs/async_client.md): update G4F async client API guide**
   - Update the G4F async client API guide with changes to the image generation model. Replace `dall-e-3` with `flux` in image generation examples. ((https://github.com/xtekky/gpt4free/pull/2304#issuecomment-2439652597))
      - Update image generation prompt to use model `flux`
      - Modify Base64 response format example to use model `flux`
      - Update concurrent tasks example to use model `flux` for image generation

> This update ensures the guide reflects the current image generation model.
---
**(docs/client.md): update G4F Client API guide**
   - Update the G4F Client API guide to include new sections and examples:
      - Added section `Creating Chat Completions`
      - Minor text and format adjustments for clarity and completeness

**(docs/client.md): add base64 response format for image generation**
   - Update G4F Client API Guide to include base64 response format
      - Modify Image Generation section to use "flux" model (https://github.com/xtekky/gpt4free/pull/2304#issuecomment-2439652597)
      - Add example for generating images in base64 response format

> This enhancement improves the documentation by providing users with additional methods for handling image data.
---
**(docs/interference-api.md): update Interference API usage guide**
   - Enhance the Interference API usage guide with detailed instructions and examples for better clarity and usability.
      - Added sections for "Using the Interference API" and "Basic Usage"
      - Introduced example curl commands for text and image generation
      - Updated existing examples with improved formatting and explanations
      - Included a "Conclusion" section to summarize the guide's content
      - Defined how to run the API from both PyPI and the repository more clearly

> These updates aim to provide a more comprehensive and user-friendly guide for integrating G4F with OpenAI-based applications.

**(docs/interference-api.md): update image generation model in usage guide**
   - Update the image generation model in the API usage guide
      - Change the image generation model from "dall-e-3" to "flux" ((https://github.com/xtekky/gpt4free/pull/2304#issuecomment-2439652597))
      - Update corresponding curl commands for both URL and b64_json response formats

> This update ensures the documentation aligns with the latest supported models.

---

### CODE REVIEW

**Comment by TheFirstNoob** [comment]
@kqlio67 Hello. Glad to see you with new changes :)
I want to attach my list of small bugs and possible improvements for better use of the library.

1. Nexra provider after the update gives an error like Provider <class 'g4f.Provider.nexra.NexraMidjourney.NexraMidjourney'> does not support image generation and this is done for all subtypes of providers regardless of which parameter to call, generate or async_generate.

Also for GPT4o the answer occurs: General (unknown error) response

2. An unknown bug occurs for random text generation providers. String out of index. I can't reproduce this bug as a permanent one, but sometimes it happens when I run tests as if the response comes earlier than it was received from the site. Perhaps it is possible to add some delays in receiving the response by 0.1?

I will also assume that after this problem all flux models began to generate images of poor quality, but here the problem is not with the provider, but with flux itself.

3. Add the ability to use a single Size parameter to configure the image size. For flux, Size is used. For SDHL and similar, the Width and Height dimensions are used. I think you can combine them and just enter the size, for example, 16x9.

4. I would like to get a little more information about how to use cloud scraper.
Some providers use it, and some do not. Is this a way to bypass captcha or region blocking? Is it possible to simply make a cloud scraper for all providers and add a variable like cloud = true/false.

**Comment by UX0l0l** [comment]
Also don't forget about the o1 issue with amigochat in #2289

**Comment by foxfire52** [comment]
After previous async update, code might need an **AsyncClient** definition for legacy script compatibility. And appropriate obsoletion warning. 
Issue #2308

**Comment by xtekky** [comment]
We definitely need to reimplement `AsyncClient` for legacy purposes, @kqlio67 would you mind adding it before i merge this pull request ?

**Comment by kqlio67** [comment]
> We definitely need to reimplement `AsyncClient` for legacy purposes, @kqlio67 would you mind adding it before i merge this pull request ?

I understand, I'll work on reimplementing AsyncClient shortly. Before proceeding, I wanted to clarify - should I:

1. Create completely separate Sync and Async implementations
2. Or keep both sync/async support in the Client class and just restore AsyncClient as a legacy wrapper with the current Client improvements?

I'll also restore the previous AsyncClient documentation. Let me know which approach you prefer, and I'll have it ready in a few minutes.

**Comment by kqlio67** [comment]
> Also don't forget about the o1 issue with amigochat in #2289

Hi @UX0l0l! Thanks for bringing this up. Regarding amigochat, I'm not sure if we'll keep this provider due to ongoing Cloudflare-related issues. It might be temporarily disabled until we find a stable solution.

As for the o1 models, I'm actively looking for providers that support these models. I'll definitely add new providers with o1 support once I find reliable options

**Comment by TheFirstNoob** [comment]
@kqlio67 Thanks! I didn't know that you can directly remake the result afterwards. I thought you need to save it and then send it. Thanks for the tip!

**Pull request merged**
