### PR TITLE
refactor models file

### PR DESCRIPTION
**Pull request by MIDORIBIN**
@xtekky 
It is an anti-pattern to have a large number of classes with the same attributes. Therefore, I have refactored the code to have only one Model class and made all other classes instances of that class.
I have made these modifications while ensuring compatibility with the existing implementation as much as possible.

### CODE REVIEW

**Comment by nonk123** [comment]
Looks like a great feature, but refactors like these should be tested on existing packages. I may be able to test it on some repos in the spare time, but I'm not sure if @xtekky is interested in this PR at all.

**Comment by MIDORIBIN** [comment]
@nonk123
Thank you for showing interest.
If this PR is merged, it will be necessary to change the import destination for 'model.'
For more details, the following should be helpful.

https://github.com/xtekky/gpt4free/pull/772/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by MIDORIBIN** [comment]
@xtekky 
If you don't want to make any breaking changes, please let me know in the comments.
I will make the necessary adjustments to revert to the original import destination. (I believe the import in this PR is correct.)

**Comment by MIDORIBIN** [comment]
@xtekky 
I have performed refactoring primarily focusing on the provider.
However, since there was a significant amount of code related to it, it turned into an overall refactoring.
Additionally, I made changes to turn inactive providers into active ones (e.g., You, Vercel, etc).

Once this PR has been merged, the PR is submitted.

**Comment by nonk123** [comment]
> Additionally, I made changes to turn inactive providers into active ones (e.g., You, Vercel, etc).

I didn't have the time to test anything myself, but it looks you did. Great job.

@xtekky No news on merging the refactor yet? If this doesn't get merged soon, it might be viable to keep the fork as a temporary, semi-official, slightly more maintained replacement for the current package. I haven't seen any activity from the main developer myself, so why bother?

**Comment by xtekky** [comment]
I was on a break sorry, will be merging this now, good job !!

**Pull request merged**
