### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by catmeowjiao**
This Pull request made the following changes:
1. Used the config.json file to add proxy support to the API and GUI.
By meowjiao
Using ChatGPT from Chinese translate to English

### CODE REVIEW

**Comment by catmeowjiao** [comment]
i will add proxy support for api, please wait 1~2 days, thanks!

**Comment by catmeowjiao** [comment]
please edit README.md, thanks!

**Comment by catmeowjiao** [comment]
please wait, api proxy coming soon

**Comment by catmeowjiao** [comment]
api proxy is testing

**Comment by catmeowjiao** [comment]
test done, i'll submit pr, please wait

**Comment by catmeowjiao** [comment]
ok

**Comment by L-Chris** [comment]
Not work, Can you give me a json example?

**Comment by catmeowjiao** [comment]
> Not work, Can you give me a json example?

@L-Chris json实例如下：
```json
{
    "proxy": "你的代理地址，如http://127.0.0.1:7890"
}
```

**Comment by piyushpranjal03** [comment]
Hey @catmeowjiao,

Thanks for adding the proxy support.
Just wanted to check how this can be used.
I can't find the usage in README file.

This is what I was trying:
```
response = g4f.ChatCompletion.create(
        model=g4f.models.default,
        provider=You,
        messages=[{"role": "user", "content": content}],
        proxy="http://107.152.47.85:9797",
        timeout=10
)
```

Can you give me some directions?

**Pull request merged**
