### PR TITLE
Streamlit chat implementation

### PR DESCRIPTION
**Pull request by repollo**
Streamlit chat app implementation, with conversation history and api select dropdown menu

EDIT: updated the code to use openai_rev package pr #218 code revisions.

### CODE REVIEW

**Comment by repollo** [comment]
Let me know when openai_rev pr_218 is implemented to modify my code to use the openai_rev package

**Comment by repollo** [comment]
Please review the commit since Im unsure why my .gitignore was literally ignored...

**Comment by xtekky** [comment]
could u update `forefront/__init__.py` please ; ) it has conflicts

**Comment by xtekky** [comment]
and the readme's

**Pull request merged**
