### PR TITLE
Added OpenChat's Aura Model as a new Provider

### LINKED ISSUE #1369: Free openchat_v3.2_mistra by OpenChat Aura API
OpenChat Aura is giving us free online demo of their openchat_v3.2_mistra and it can be used to add as a new model to this repo!
online demo: https://openchat.team/

### PR DESCRIPTION
**Pull request by devAdityaa**
Created a new Provider for Aura by Openchat which provides a free GPT 3.5 based model.
Closes #1369

### CODE REVIEW

**Comment by Recentaly** [comment]
the ``prompt`` parameter is used for system messages. Leaving it empty and passing the system prompt in the ``messages`` parameter isn't sufficient.

**Comment by devAdityaa** [comment]
> the ``prompt`` parameter is used for system messages. Leaving it empty and passing the system prompt in the ``messages`` parameter isn't sufficient.

The prompt parameter remains empty when we send the request in the original site. Our Chats are sent in the messages parameter. 
I can set the prompt to some system message like "You are an AI assistant based on GPT 3.5...." but it wasn't mentioned in the contribution docs that's why I left it empty.
Either way it doesn't break the request.
What do you suggest?

**Comment by devAdityaa** [comment]
Ohh! I see... Thanks for pointing out. Missed the system message part.
Will code it and resend the PR.
Thanks again!

**Comment by devAdityaa** [comment]
@Recentaly  Done, I have added the two seperate variables for system message and system prompts. Please check once. Thanks.

**Review by Recentaly — CHANGES_REQUESTED** [review]
Lowercase the "System"

From: 

```py
if message["role"]=="System":
    system_prompt +=message["content"]
else:
    system_message.append(message)
```

To:

```py
if message["role"]=="system": # LOWERCASE 'S'
    system_prompt +=message["content"]
else:
    system_message.append(message)
```

Reason: OpenAI format specifies a strictly lowercase 'system'

**Review by Recentaly — CHANGES_REQUESTED** [review]
Revert Change. 

Reason: Formatting messages (type list) to a string causes Internal Server Error.

Error log:

  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://openchat.team/api/chat

Suggestion: Continue passing messages as a list

```py
...
"messages": system_message,
...
```

**Comment by devAdityaa** [comment]
Yeah I checked it, the messages should be passed as a list. My bad. I've changed both of them. Kindly check once.

**Review by Recentaly — APPROVED** [review]

**Comment by devAdityaa** [comment]
@hlohaus can you please give any suggestions for this PR

**Comment by hlohaus** [comment]
streaming is not working. but i can fix it fast

**Comment by devAdityaa** [comment]
> streaming is not working. but i can fix it fast

Ok thanks!

**Pull request merged**
