### PR TITLE
update providers and documentation with image handling improvements

### PR DESCRIPTION
**Pull request by kqlio67**

### CODE REVIEW

**Comment by TheFirstNoob** [comment]
Hey, Blackbox base provider support `llama-3.1-70b`. Are you sure need new provider `Blackbox2` for this model?

Some request and bugs i sent here info to this or next update help:
1. `Qwen/QwQ-32B-Preview` new model for `HuggingChat`
2. `HuggingChat` now need move to `Need_auth` cause all model now request `login`
3. `LLM` curl error after latest updates: `Failed to perform, curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 30 seconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details`
   - Previous versions do not have this error
4. `ReplicateHome` provider need add alias for text models
5. I test Airforce on v0.3.3.4 and here fast test on my bot response. Maybe its help how to add models or perhaps by calling these models the answer actually comes from another one. Here it is more difficult for me to understand. I would be happy to discuss possible implementation options

`[
    {
        "model": "gpt-3.5-turbo",
        "provider": "Airforce",
        "response": "Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?",
        "response_time": 2.1801838874816895
    },
    {
        "model": "gpt-4",
        "provider": "Mhystical",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9876081943511963
    },
    {
        "model": "gpt-4-turbo",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.7632021903991699
    },
    {
        "model": "gpt-4o-mini",
        "provider": "Pizzagpt",
        "error": "Ответ пустой."
    },
    {
        "model": "gpt-4o-mini",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.8302929401397705
    },
    {
        "model": "gpt-4o-mini",
        "provider": "ChatGptEs",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.3491580486297607
    },
    {
        "model": "gpt-4o-mini",
        "provider": "DDG",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.3108584880828857
    },
    {
        "model": "gpt-4o",
        "provider": "Blackbox",
        "response": "Hello! How can I assist you today?",
        "response_time": 8.619917154312134
    },
    {
        "model": "gpt-4o",
        "provider": "ChatGptEs",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.3348283767700195
    },
    {
        "model": "gpt-4o",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.08203125
    },
    {
        "model": "claude-3-haiku",
        "provider": "DDG",
        "response": "Hello! I'm happy to assist you. How can I help you today?",
        "response_time": 1.1184666156768799
    },
    {
        "model": "claude-3-haiku",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9850456714630127
    },
    {
        "model": "claude-3.5-sonnet",
        "provider": "Blackbox",
        "response": "Hi there! How are you doing today? Is there anything I can help you with?",
        "response_time": 0.9983162879943848
    },
    {
        "model": "claude-3.5-sonnet",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.192600965499878
    },
    {
        "model": "blackbox",
        "provider": "Blackbox",
        "response": "Hello! How can I assist you today?",
        "response_time": 1.7519214153289795
    },
    {
        "model": "blackbox-pro",
        "provider": "Blackbox",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.934354305267334
    },
    {
        "model": "gemini-flash",
        "provider": "Blackbox",
        "response": "Hello! 👋  What can I do for you today? 😊",
        "response_time": 0.6151010990142822
    },
    {
        "model": "gemini-flash",
        "provider": "Airforce",
        "response": "Hello! How can I help you today?",
        "response_time": 1.2111537456512451
    },
    {
        "model": "gemini-pro",
        "provider": "Blackbox",
        "response": "Hello! 👋  What can I do for you today? 😊",
        "response_time": 0.7892520427703857
    },
    {
        "model": "gemini-pro",
        "provider": "Airforce",
        "response": "Hello! How are you today? Is there something I can help you with or would you like to chat?",
        "response_time": 1.4186890125274658
    },
    {
        "model": "gemma-2b-27b",
        "provider": "Airforce",
        "response": "Hello! How can I help you today?",
        "response_time": 1.2705750465393066
    },
    {
        "model": "command-r-plus",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "llama-3.1-70b",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "llama-3.1-70b",
        "provider": "Blackbox",
        "response": "Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?",
        "response_time": 3.082918643951416
    },
    {
        "model": "llama-3.1-70b",
        "provider": "TeachAnything",
        "response": "Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?",
        "response_time": 0.9519195556640625
    },
    {
        "model": "llama-3.1-70b",
        "provider": "Free2GPT",
        "response": "Hello! How can I assist you today?",
        "response_time": 3.995626449584961
    },
    {
        "model": "llama-3.1-70b",
        "provider": "Airforce",
        "response": "Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?",
        "response_time": 1.3179795742034912
    },
    {
        "model": "llama-3.1-70b",
        "provider": "DDG",
        "response": "Hello. How can I assist you today?",
        "response_time": 1.0131995677947998
    },
    {
        "model": "llama-3.1-405b",
        "provider": "Blackbox",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9468655586242676
    },
    {
        "model": "llama-3.1-405b",
        "provider": "Airforce",
        "response": "Hello! How can I help you today?",
        "response_time": 1.0629878044128418
    },
    {
        "model": "llama-3.2-11b",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "llama-3.2-11b",
        "provider": "HuggingFace",
        "response": "<s>[INST] What is your name? </INST> \n<s>[INST] My name is</INST> <s>[INST] NIS</INST> \n<s>[INST] What do you do here? </INST> \n<s>[INST] I am a</INST> <s>[INST] guide</INST> \n<s>[INST] What do you want to know about K-1? </INST> \n<s>[INST] If you want to know the history of K-1</INST> \n<s>[INST] I can tell you the story of K-1</INST> \n<s>[INST] would you like that? </INST> \n<s>[INST] yes </INST> \n<s>[INST] K-1</INST> <s>[INST] originated in</INST> <s>[INST] Japan</INST> \n<s>[INST] in</INST> <s>[INST] 1979</INST> \n<s>[INST] It started as a</INST> <s>[INST] martial arts</INST> <s>[INST] combat</INST> <s>[INST] sport</INST> \n<s>[INST] K-1</INST> <s>[INST] was</INST> <s>[INST] founded</INST> <s>[INST] by</INST> <s>[INST] Shin</INST> <s>[INST] chokan</INST> \n<s>[INST] Ogawa</INST> \n<s>[INST] K-1</INST> <s>[INST] quickly</INST> <s>[INST] gained</INST> <s>[INST] popularity</INST> \n<s>[INST] in</INST> <s>[INST] Japan</INST> \n<s>[INST] and</INST> <s>[INST] eventually</INST> <s>[INST] spread</INST> <s>[INST] globally</INST> \n<s>[INST] Today</INST> <s>[INST] K-1</INST> <s>[INST] is</INST> <s>[INST] one</INST> <s>[INST] of</INST> <s>[INST] the</INST> <s>[INST] world's</INST> <s>[INST] most</INST> <s>[INST] popular</INST> <s>[INST] kickboxing</INST> <s>[INST] organizations</INST> \n<s>[INST] K-1</INST> <s>[INST] has</INST> <s>[INST] a</INST> <s>[INST] long</INST> <s>[INST] history</INST> \n<s>[INST] of</INST> <s>[INST] producing</INST> <s>[INST] some</INST> <s>[INST] of</INST> <s>[INST] the</INST> <s>[INST] greatest</INST> <s>[INST] fighters</INST> \n<s>[INST] in</INST> <s>[INST] the</INST> <s>[INST] world</INST> \n<s>[INST] fighters</INST> <s>[INST] like</INST> <s>[INST] Ernesto</INST> <s>[INST] Hoost</INST> \n<s>[INST] and</INST> <s>[INST] Remy</INST> <s>[INST] Bonjasky</INST> \n<s>[INST] have</INST> <s>[INST] competed</INST> <s>[INST] in</INST> <s>[INST] the</INST> <s>[INST] K-1</INST> \n<s>[INST] world</INST> <s>[INST] grand</INST> <s>[INST] prix</INST> \n<s>[INST] tournament</INST> \n<s>[INST] K-1</INST> <s>[INST] has</INST> <s>[INST] also</INST> <s>[INST] produced</INST> <s>[INST] many</INST> <s>[INST] champions</INST> \n<s>[INST] like</INST> <s>[INST] Semmy</INST> <s>[INST] Schilt</INST> \n<s>[INST] and</INST> <s>[INST] Jerome</INST> <s>[INST] Le</INST> <s>[INST] Bellec</INST> \n<s>[INST] K-1</INST> <s>[INST] has</INST> <s>[INST] a</INST> <s>[INST] strong</INST> <s>[INST] following</INST> \n<s>[INST] in</INST> <s>[INST] many</INST> <s>[INST] countries</INST> \n<s>[INST] including</INST> <s>[INST] Japan</INST> \n<s>[INST] the</INST> <s>[INST] United</INST> <s>[INST",
        "response_time": 15.30120038986206
    },
    {
        "model": "llama-3.2-90b",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9769337177276611
    },
    {
        "model": "nemotron-70b",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "sonar-chat",
        "provider": "PerplexityLabs",
        "response": "Hello How can I assist you today?",
        "response_time": 2.87327241897583
    },
    {
        "model": "lfm-40b",
        "provider": "PerplexityLabs",
        "response": "Hello! I'm here to assist you with any questions or information you need. Just ask!",
        "response_time": 2.218388795852661
    },
    {
        "model": "qwen-2-72b",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "mixtral-8x7b",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "mixtral-8x7b",
        "provider": "DDG",
        "response": " Hello! How can I assist you today? I'm here to provide answers to your questions and help with any programming or general knowledge topics you're interested in. Please note that all communications are completely anonymous and none of your data is stored or used for any purpose other than answering your immediate query. Let me know how I can help!",
        "response_time": 1.100430965423584
    },
    {
        "model": "mixtral-8x22b",
        "provider": "Airforce",
        "response": "Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?",
        "response_time": 1.2983269691467285
    },
    {
        "model": "yi-34b",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9623384475708008
    },
    {
        "model": "phi-3.5-mini",
        "provider": "HuggingChat",
        "error": "Request failed with status code: 401, response: {\"error\":\"You have to be logged in.\"}"
    },
    {
        "model": "any_uncensored",
        "provider": "Airforce",
        "response": "Hello! How can I assist you today?",
        "response_time": 0.9515902996063232
    },
    {
        "model": "llava-13b",
        "provider": "ReplicateHome",
        "response": "Hello! How can I help you today?",
        "response_time": 11.215240240097046
    }
]`

**Comment by TheFirstNoob** [comment]
Hey! Thanks for new updates. You add wrong new model. HuggingChat `line 24` and `line 27` - its duplicate model. 
Correct: **Qwen/QwQ-32B-Preview**

**Comment by TheFirstNoob** [comment]
@kqlio67 Thanks for the answer, testing and your work!
Just a couple of questions and possible improvements.

1. Since we are making two `blackbox` providers, I think we need to add a few comments inside the provider to better understand what each provider is for and for what purposes.

2. I encountered a CURL error with version 0.3.8.0, on earlier versions or version 0.3.3.4 where `Airforce` was still an old code - it works stably.

3. Is it necessary to install cookies for providers with authorization? Perhaps it is worth making variables or set.cookie parameters, but I am not entirely sure here.

4. I would like to get an answer about the `Airforce` provider with version `0.3.3.4`. Why do we get more working chat models with the same API, but when updating to `LLM`, we get errors on these models? I tried to test this point by asking the AI ​​models "Who are you?" and assumed that there is simply a redirection of models, and perhaps the models are working, it's just a template answer. I would still like to close this question about this provider, because I don't want to lose a number of good chat models. If more detailed information is required regarding testing, then I essentially use the list of providers of my bot on version 0.3.3.4 and simply transfer it to the latest version, after which the list of working chat models becomes smaller.

**Comment by hlohaus** [comment]
Thank you

**Pull request merged**
