### PR TITLE
add V50 Provider & refactor Raycast (need testing with auth)

### PR DESCRIPTION
**Pull request by bagusindrayana**
from https://github.com/xtekky/gpt4free/issues/40#issuecomment-1660796234
but redirect to https://p5.v50.ltd so I named it V50

### CODE REVIEW

**Comment by xtekky** [comment]
can you change your code to fit the new format ?:

```
from abc import ABC, abstractmethod

from ..typing import Any, CreateResult


class BaseProvider(ABC):
    url: str
    working = False
    needs_auth = False
    supports_stream = False
    supports_gpt_35_turbo = False
    supports_gpt_4 = False

    @staticmethod
    @abstractmethod
    def create_completion(
        model: str,
        messages: list[dict[str, str]],
        stream: bool,
        **kwargs: Any,
    ) -> CreateResult:
        raise NotImplementedError()

    @classmethod
    @property
    def params(cls):
        params = [
            ("model", "str"),
            ("messages", "list[dict[str, str]]"),
            ("stream", "bool"),
        ]
        param = ", ".join([": ".join(p) for p in params])
        return f"g4f.provider.{cls.__name__} supports: ({param})"
```

more info in the "contributing" section of the README

**Comment by xtekky** [comment]
good job !

**Comment by johnd0e** [comment]
V50 is not free
`卡卡密密错错误误，，请请检检查查卡卡密密或或前前往往 https://fk1.v50.ltd 购购买买卡卡密`

**Comment by bagusindrayana** [comment]
> V50 is not free `卡卡密密错错误误，，请请检检查查卡卡密密或或前前往往 https://fk1.v50.ltd 购购买买卡卡密`

you right, today they api is behind paywall, i mean yesterday i can use it and tested 10+ request.
i think i need tested based on time/day not how many request, because some random website in [suggestion issue](https://github.com/xtekky/gpt4free/issues/40) always change they pricing, domain, api endpoint or even will shutdown immediately.

disable this provider in next pull request

**Pull request merged**
