### PR TITLE
Fix Gemini Proxy Connect call failed

### PR DESCRIPTION
**Pull request by HyiKi**
The error is as follows:
```plain text
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lh3.googleusercontent.com:443 ssl:default [Connect call failed ('172.217.163.33', 443)]
```
fix issue: Gemini.py missing proxy setting at line 141 and 143

### CODE REVIEW

**Comment by ebullienc3** [comment]
Does this should fix the problems with using chat and images from Gemeni? 
Because I tried it and the bot freezes on "Botname is thinking..."

**Comment by HyiKi** [comment]
> Does this should fix the problems with using chat and images from Gemeni? Because I tried it and the bot freezes on "Botname is thinking..."

@ebullienc3 The following is my example code. When I configure the proxy to execute this code, there will be errors in the main text. My changes have solved this problem.
```python
client = Client()
response = client.images.generate(
  model="gemini",
  prompt="cute cat"
)
image_url = response.data[0].url
```
My usage is Gemini image generation. Tell me what your problem function is, and I should be able to help you.

**Comment by ebullienc3** [comment]
> > Does this should fix the problems with using chat and images from Gemeni? Because I tried it and the bot freezes on "Botname is thinking..."
> 
> @ebullienc3 The following is my example code. When I configure the proxy to execute this code, there will be errors in the main text. My changes have solved this problem.
> 
> ```python
> client = Client()
> response = client.images.generate(
>   model="gemini",
>   prompt="cute cat"
> )
> image_url = response.data[0].url
> ```
> 
> My usage is Gemini image generation. Tell me what your problem function is, and I should be able to help you.

I am using this bot in Discord https://github.com/Zero6992/chatGPT-discord-bot
Whenever I try to use /draw with model Gemeni or Bing I get this: Error Message:Create images failed: we can't create your images right now.

**Comment by HyiKi** [comment]
> > > Does this should fix the problems with using chat and images from Gemeni? Because I tried it and the bot freezes on "Botname is thinking..."
> > 
> > 
> > @ebullienc3 The following is my example code. When I configure the proxy to execute this code, there will be errors in the main text. My changes have solved this problem.
> > ```python
> > client = Client()
> > response = client.images.generate(
> >   model="gemini",
> >   prompt="cute cat"
> > )
> > image_url = response.data[0].url
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My usage is Gemini image generation. Tell me what your problem function is, and I should be able to help you.
> 
> I am using this bot in Discord https://github.com/Zero6992/chatGPT-discord-bot Whenever I try to use /draw with model Gemeni or Bing I get this: Error Message:Create images failed: we can't create your images right now.

Okay, your problem is not related to this repository, but I guess it should be a network issue.

**Comment by ebullienc3** [comment]
It is indeed for here as the bot is using gpt4free. Anyways, I opened another issue. Thanks :)

**Comment by HyiKi** [comment]
> It is indeed for here as the bot is using gpt4free. Anyways, I opened another issue. Thanks :)

The same issue here. https://github.com/Zero6992/chatGPT-discord-bot/issues/501

**Comment by hlohaus** [comment]
Also you could add the get_connector helper for socks proxy support. Then you doesn't need to pass the proxy everywhere.

**Comment by HyiKi** [comment]
> Also you could add the get_connector helper for socks proxy support. Then you doesn't need to pass the proxy everywhere.

@hlohaus Okay, updated.

**Comment by hlohaus** [comment]
Thank you very much

**Pull request merged**
