### PR TITLE
Create z1

### PR DESCRIPTION
**Pull request by lovelife0321**
oh yeah

### CODE REVIEW

**Review by rmondal-official — CHANGES_REQUESTED** [review]
## What change have you made? Please don't waste other people's time !
Don't waste valuable time by submitting a pull request without making significant changes to the code first. Make sure your modifications are reasonable and well thought out. Your efforts will not only benefit you, but also contribute to the overall success of the project.

**Comment by lovelife0321** [comment]
I’m really sorry. I’m still learning how to understand this usage. I’m a
beginner. I’m sorry, I’m sorry.🙇🏻‍♀️

H Lohaus ***@***.***>於 2024年3月26日 週二，下午5:26寫道：

**Comment by lovelife0321** [comment]
I’m really sorry. I’m still learning how to understand this usage. I’m a
beginner. I’m sorry, I’m sorry.😭


Rajesh Mondal ***@***.***>於 2024年3月26日 週二，下午3:33寫道：

**Comment by lovelife0321** [comment]
我的錯

**Comment by lovelife0321** [comment]
> What change did you make? Please don't waste other people's time! > Don't waste valuable time by submitting a pull request without making significant changes to the code first. Make sure your changes are reasonable and well thought out. Your efforts will not only benefit you, but also contribute to the overall success of the project.

I apologise for the misunderstanding earlier. At first I thought I was successful, but now I realise that's not the case. I will try to learn more and improve. Thank you for your guidance and I will work hard to improve.

**Comment by RajeshTechForge** [comment]
Wishing you all the best on your learning journey!

**Comment by RajeshTechForge** [comment]
> I apologise for the misunderstanding earlier. At first I thought I was successful, but now I realise that's not the case. I will try to learn more and improve. Thank you for your guidance and I will work hard to improve.

Wishing you all the best on your learning journey!

**Pull request closed without merging**
