### PR TITLE
Add Auth Option and some other improvement

### PR DESCRIPTION
**Pull request by cckuailong**
1. Add auth option
2. Beautify the gui/streamlit_app.py
3. Improve the Dockefile
4. Add a docker-compose.yml
5. Update Readme

### CODE REVIEW

**Comment by BrokenTek** [comment]
Accept

**Comment by cckuailong** [comment]
Also solve some bugs like [issues/271](https://github.com/xtekky/gpt4free/issues/271)

**Comment by Diyago** [comment]
@cckuailong seems this pr still doesnt fix #271 (

**Comment by 6vision** [comment]
error still
image

**Comment by gran4** [comment]
Also, I think you should make separate PRs for different (unrelated)issues.

**Comment by cckuailong** [comment]
> Also, I think you should make separate PRs for different (unrelated)issues.

Oh, you are right, but when I add a new feature, I find many bugs which affect the feature. How many PR should I make? If you don't like it, please stay away from it.

**Comment by cckuailong** [comment]
> error still
> image
> 

They are not the same error………

**Comment by gran4** [comment]
> > Also, I think you should make separate PRs for different (unrelated)issues.
> 
> Oh, you are right, but when I add a new feature, I find many bugs which affect the feature. How many PR should I make? If you don't like it, please stay away from it.

@cckuailong chill. I only said to keep separate issues in separate PRs. If they are related to the issue, its ok,

**Pull request closed without merging**
