### PR TITLE
Docker Support for gpt4free

### PR DESCRIPTION
**Pull request by krjordan**
## Overview:
This PR introduces Docker support to simplify the setup and usage of the gpt4free project, making it more accessible to developers and ensuring a consistent environment.

## Changes:
- Added `Dockerfile` to define the container environment.
- Added `docker-compose.yml` for easy setup and orchestration.
- Updated `README.md` with instructions on how to use Docker to set up and run the project.

## How to Test:
1. Ensure Docker and docker-compose are installed.
2. Clone this branch.
3. Run `docker-compose up` from the project root.
4. The application should be accessible at `http://localhost:1337`.

Please review and provide feedback. If there are any issues or improvements needed, I'm open to making the necessary changes. Thank you for considering this contribution!

### CODE REVIEW

**Comment by m4tt72** [comment]
I'm getting this error when running the container:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/interference/app.py", line 11, in <module>
    from g4f import ChatCompletion
  File "/app/g4f/__init__.py", line 1, in <module>
    from . import models
  File "/app/g4f/models.py", line 3, in <module>
    from .Provider import Bard, BaseProvider, GetGpt, H2o, Liaobots, Vercel, Equing
  File "/app/g4f/Provider/__init__.py", line 6, in <module>
    from .Bard import Bard
  File "/app/g4f/Provider/Bard.py", line 11, in <module>
    class Bard(AsyncProvider):
  File "/app/g4f/Provider/Bard.py", line 22, in Bard
    cookies: dict = get_cookies(".google.com"),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/g4f/Provider/base_provider.py", line 45, in get_cookies
    for cookie in browser_cookie3.load(cookie_domain):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1233, in load
    for cookie in cookie_fn(domain_name=domain_name):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1160, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 626, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file,
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 416, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 431, in __add_key_and_cookie_file
    USE_DBUS_LINUX).get_password(os_crypt_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 232, in get_password
    return self.__get_secretstorage_password(os_crypt_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 247, in __get_secretstorage_password
    return self.__methods_map.get('secretstorage')(schema, os_crypt_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 303, in __get_secretstorage_item_jeepney
    with _JeepneyConnection(*args) as connection:
  File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 195, in __enter__
    self.__connection = open_dbus_connection()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jeepney/io/blocking.py", line 341, in open_dbus_connection
    bus_addr = get_bus(bus)
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```

Any idea how to fix it?

**Comment by m4tt72** [comment]
> I'm getting this error when running the container:
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/app/interference/app.py", line 11, in <module>
>     from g4f import ChatCompletion
>   File "/app/g4f/__init__.py", line 1, in <module>
>     from . import models
>   File "/app/g4f/models.py", line 3, in <module>
>     from .Provider import Bard, BaseProvider, GetGpt, H2o, Liaobots, Vercel, Equing
>   File "/app/g4f/Provider/__init__.py", line 6, in <module>
>     from .Bard import Bard
>   File "/app/g4f/Provider/Bard.py", line 11, in <module>
>     class Bard(AsyncProvider):
>   File "/app/g4f/Provider/Bard.py", line 22, in Bard
>     cookies: dict = get_cookies(".google.com"),
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/g4f/Provider/base_provider.py", line 45, in get_cookies
>     for cookie in browser_cookie3.load(cookie_domain):
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1233, in load
>     for cookie in cookie_fn(domain_name=domain_name):
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1160, in chrome
>     return Chrome(cookie_file, domain_name, key_file).load()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 626, in __init__
>     super().__init__(browser='Chrome', cookie_file=cookie_file,
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 416, in __init__
>     self.__add_key_and_cookie_file(**kwargs)
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 431, in __add_key_and_cookie_file
>     USE_DBUS_LINUX).get_password(os_crypt_name)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 232, in get_password
>     return self.__get_secretstorage_password(os_crypt_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 247, in __get_secretstorage_password
>     return self.__methods_map.get('secretstorage')(schema, os_crypt_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 303, in __get_secretstorage_item_jeepney
>     with _JeepneyConnection(*args) as connection:
>   File "/usr/local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 195, in __enter__
>     self.__connection = open_dbus_connection()
>                         ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/jeepney/io/blocking.py", line 341, in open_dbus_connection
>     bus_addr = get_bus(bus)
>                ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/jeepney/bus.py", line 53, in get_bus
>     return find_session_bus()
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/jeepney/bus.py", line 42, in find_session_bus
>     addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
>            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen os>", line 679, in __getitem__
> KeyError: 'DBUS_SESSION_BUS_ADDRESS'
> ```
> 
> Any idea how to fix it?

Okay fixed by adding a custom script:

```bash
#!/usr/bin/env bash

set -e

export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --fork --config-file=/usr/share/dbus-1/session.conf --print-address`

python -m interference.app
```

And in the `Dockerfile` I made sure `dbus` is installed.

```Dockerfile
FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  build-essential \
  git \
  dbus \
  && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install -r requirements.txt
RUN pip install -r interference/requirements.txt

COPY run.sh /app/run.sh

RUN chmod +x /app/run.sh

CMD ["/bin/bash", "/app/run.sh"]
```

**Comment by Josh-XT** [comment]
PR #855 will fix the errors you're getting once it is merged.

**Comment by xtekky** [comment]
I am not familiar with this solution, but I will check it out this week.

**Review by Josh-XT — APPROVED** [review]
Looks good

**Pull request merged**
