### PR TITLE
added some more providers

### PR DESCRIPTION
**Pull request by najam-tariq**
1. AItianhu
2. EasyChat
3. Acytoo
4. DFEHub

### CODE REVIEW

**Comment by xtekky** [comment]
good job !

**Comment by phamxtien** [comment]
1. g4f.Provider.Providers.Acytoo provider returns <Response [429]>
2. g4f.Provider.Providers.DFEHub provider return Error Occurred::405

**Comment by najam-tariq** [comment]
@phamxtien 
1. Acytoo is not working atm — technical issue on the Provider's side
2. Fixed DFEHub temporarily by implementing support for rate-limit, but I think @xtekky would be able to come up with a better solution (probably bypass rate-limit?)

**Comment by phamxtien** [comment]
EasyChat got error: 
Error Occurred::403

**Pull request merged**
