### PR TITLE
Fix bing provider

### PR DESCRIPTION
**Pull request by hlohaus**

### CODE REVIEW

**Comment by phamxtien** [comment]
It returns error:
AsyncProvider.create_completion() got multiple values for argument 'cls'

**Comment by hlohaus** [comment]
This PR hast a fix: https://github.com/xtekky/gpt4free/pull/844/files#diff-2e095978f4420600f8dd5df9c124f4e38189ef0efcfd80694a32f25e16cf1b96L80

**Comment by phamxtien** [comment]
After update the code it returns:
message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://sydney.bing.com/sydney/DeleteSingleConversation')

**Comment by hlohaus** [comment]
Everytime when you use Bing? Or only once? I can use Bing without Problems. You have to Pass the captcha Challenge in the Browser. The Captcha comes when a new Chat are created.

**Comment by phamxtien** [comment]
> Everytime when you use Bing? Or only once? I can use Bing without Problems. You have to Pass the captcha Challenge in the Browser. The Captcha comes when a new Chat are created.

On first time, but get error :(
I'm still trying

**Pull request merged**
