### PR TITLE
Fix api streaming, fix AsyncClient

### PR DESCRIPTION
**Pull request by hlohaus**

### CODE REVIEW

**Comment by xtekky** [comment]
`AsyncClient` was removed by @kqlio67, do we want to reimplement it again ?

**Comment by hlohaus** [comment]
A single file is acceptable, but your implementation is not functioning as intended.

**Comment by TheFirstNoob** [comment]
@hlohaus hI AsyncDDGS class should be use `atext` if you want use non-async use `import DDGS` class

**Comment by hlohaus** [comment]
No message received

**Comment by hlohaus** [comment]
# Pull Request Review

### Author: H Lohaus
### Title: Fix api streaming, fix AsyncClient

---

Thank you for contributing to the project! Your changes look good and will enhance the functionality of our API by fixing the streaming issues and transitioning to an asynchronous client. Here are some specific points:

1. **Changes in `__init__.py`**:
   - The transition from `Client` to `AsyncClient` is an essential update that aligns well with the modern needs of handling asynchronous requests.

2. **New `async_client.py`**:
   - Excellent job implementing the `AsyncClient`. It looks comprehensive and provides good async capabilities for the class. The structure is clear, and the comments help in understanding the flow.

3. **Modifications in `client.py`**:
   - I noticed you removed the legacy `AsyncClient` class for better clarity and to avoid confusion. This is a great decision moving forward!

4. **Streaming Responses**:
   - Changing the handling of non-streaming responses to utilize async features shows good forward-thinking about performance and user experience. 

5. **General Code Quality**:
   - The overall code looks clean, well-organized, and adheres to our coding standards. This is appreciated!

Before merging, I recommend running a full set of tests to ensure nothing breaks. If everything passes, I’m excited to see this merged!

Once again, thank you for your efforts on this pull request. Your work substantially improves our API&#39;s capabilities!

**Comment by TheFirstNoob** [comment]
Hey! Latest pull update have outdated version code g4f? Some changes/providers and code looks old like 0.3.3.3 version.
Version conflicts merge?

**Pull request merged**
