### PR TITLE
fix: #369, Proxy support(both http and socks5).

### PR DESCRIPTION
**Pull request by Civitasv**
When specify proxy, for http, we can use format of `http://proxyhost:port`, for socks5, we can use format of `socks5h://proxyhost:port`.

Also, I've added proxy support for gui of `streamlit_app.py`.

### CODE REVIEW

**Comment by Civitasv** [comment]
See #369.

**Comment by Civitasv** [comment]
Please consider merge this pull request, it can fix many issues about connection, @xtekky. Thanks advance :smile: !

**Comment by z-x-x136** [comment]
> 指定代理时，对于http，我们可以使用格式`http://proxyhost:port`，对于socks5，我们可以使用格式`socks5h://proxyhost:port`。
> 
> 此外，我还添加了对 .gui 的代理支持`streamlit_app.py`。

My agent is http://127.0.0.1:33210. Where do I get it from the program?

**Comment by Civitasv** [comment]
just use: `proxy = http://127.0.0.1:33210`

**Pull request closed without merging**
