### PR TITLE
update header & response easychat

### PR DESCRIPTION
**Pull request by bagusindrayana**
fix forbidden error
```bash
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chat4.fastgpt.me/api/openai/v1/chat/completions
```
add one server `https://gxos1h1ddt.fastgpt.me`
update response check (status, length, etc) and exception

### CODE REVIEW

**Comment by johnd0e** [comment]
`stream=False`
Sometimes it is works, but more often just throws (after delay):
```
Traceback (most recent call last):
  File "D:\AI\gpt4free\nostream.py", line 3, in <module>
    response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.EasyChat, messages=[
  File "D:\AI\gpt4free\g4f\__init__.py", line 45, in create
    return result if stream else "".join(result)
TypeError: sequence item 0: expected str instance, Exception found
```
`stream=True`
Response is this mess:
```
>

p
r
o
v
i
d
e
d

b
y

[
E
a
s
y
C
h
a
t
]
(
h
t
t
p
s
:
/
/
N
J
2
J
R
T
X
i
8
H
.
f
a
s
t
g
p
t
.
m
e
/
)
```

**Comment by bagusindrayana** [comment]
> `stream=False` Sometimes it is works, but more often just throws (after delay):
> 
> ```
> Traceback (most recent call last):
>   File "D:\AI\gpt4free\nostream.py", line 3, in <module>
>     response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.EasyChat, messages=[
>   File "D:\AI\gpt4free\g4f\__init__.py", line 45, in create
>     return result if stream else "".join(result)
> TypeError: sequence item 0: expected str instance, Exception found
> ```
> 
> `stream=True` Response is this mess:
> 
> ```
> >
> 
> p
> r
> o
> v
> i
> d
> e
> d
> 
> b
> y
> 
> [
> E
> a
> s
> y
> C
> h
> a
> t
> ]
> (
> h
> t
> t
> p
> s
> :
> /
> /
> N
> J
> 2
> J
> R
> T
> X
> i
> 8
> H
> .
> f
> a
> s
> t
> g
> p
> t
> .
> m
> e
> /
> )
> ```

thank you for your review, first error maybe happen if response from provider is `""` or empty string, i try to figure out to make sure provider dont return empty string and keep continue or raise exception

second problem happen because whitespace in split `chunk.decode().split("data: ")`, from previous commit already use it but now seem not work so temporary fix to remove whitespace from `"data: "` to `"data:"`

i will fix in next PR (or maybe someone else first if anyone wants)

**Comment by bagusindrayana** [comment]
> `stream=False` Sometimes it is works, but more often just throws (after delay):
> 
> ```
> Traceback (most recent call last):
>   File "D:\AI\gpt4free\nostream.py", line 3, in <module>
>     response = g4f.ChatCompletion.create(model='gpt-3.5-turbo', provider=g4f.Provider.EasyChat, messages=[
>   File "D:\AI\gpt4free\g4f\__init__.py", line 45, in create
>     return result if stream else "".join(result)
> TypeError: sequence item 0: expected str instance, Exception found
> ```
> 
> `stream=True` Response is this mess:
> 
> ```
> >
> 
> p
> r
> o
> v
> i
> d
> e
> d
> 
> b
> y
> 
> [
> E
> a
> s
> y
> C
> h
> a
> t
> ]
> (
> h
> t
> t
> p
> s
> :
> /
> /
> N
> J
> 2
> J
> R
> T
> X
> i
> 8
> H
> .
> f
> a
> s
> t
> g
> p
> t
> .
> m
> e
> /
> )
> ```

@johnd0e i make PR https://github.com/xtekky/gpt4free/pull/838 maybe you want check it

**Comment by johnd0e** [comment]
Error 403 from server

**Comment by bagusindrayana** [comment]
> At the moment: `Error 403 from server` Tried with different subdomains.
> 
> Maybe because of captcha?

I think, they add hcaptcha recently, good for them to prevent scraping. Idk how to bypass that so maybe wait someone that can bypass or just use another provider

**Pull request merged**
