### PR TITLE
Create requests.md

### PR DESCRIPTION
**Pull request by ufoptg**

### CODE REVIEW

**Comment by hlohaus** [comment]
Thank you.
Can you add a link in the Readme too?

**Comment by ufoptg** [comment]
> Thank you. Can you add a link in the Readme too? And can you use localhost as host for the examples

Yes

**Comment by ufoptg** [comment]
> Thank you. Can you add a link in the Readme too? And can you use localhost as host for the examples

I also created another requests method to handle streams

**Comment by ufoptg** [comment]
> Thank you. Can you add a link in the Readme too? And can you use localhost as host for the examples

Did you mean a link to this file ?

**Comment by ufoptg** [comment]
Is that better ?

**Comment by hlohaus** [comment]
Yeah, a link in the readme is good.

Also, tell them they have to start the API via the CLI or Docker environment.

And that they can find a Swagger UI documentation on the URL localhost:1337/docs

**Comment by hlohaus** [comment]
Thank you!

**Pull request merged**
