### PR TITLE
Auto-generate PR description [G4F]

### PR DESCRIPTION
**Pull request by yuri-val**
🎉 **Feature Addition: Auto-generate Pull Request Descriptions!** 🎉

This PR introduces a new GitHub Actions workflow that automatically generates descriptions for pull requests when they are opened or synchronized. 

### Key Changes:
- 🛠️ Added a new workflow file: `.github/workflows/auto-pr-description.yml`
- 🔄 The workflow triggers on pull request events (opened and synchronized).
- 🚀 Utilizes the `yuri-val/auto-pr-description-g4f-action` to create informative PR descriptions automatically.
  - https://github.com/yuri-val/auto-pr-description-g4f-action
  - https://github.com/marketplace/actions/auto-generate-pr-description-g4f

### Benefits:
- 📋 Saves time by automating PR description generation.
- 🔍 Enhances clarity and consistency in pull request management.

Let's streamline our workflow and improve collaboration! 🚀

### CODE REVIEW

**Comment by yuri-val** [comment]
Yes, you are right. It's just a "free" rewrote to Python version of main action

**Comment by yuri-val** [comment]
You should also check repo Action permissions 
Repo -> Settings -> Actions -> General

**Comment by yuri-val** [comment]
@hqnicolas 

Your workflow looks mostly correct, but the permission issue (403: Resource not accessible by integration) could still arise if the default GitHub token lacks appropriate scope. Below are a few recommendations to troubleshoot and resolve the error:

1. Adjust permissions Settings

The permissions you’ve set (pull-requests: write, issues: write) should generally be sufficient, but sometimes GitHub’s permission model requires more than expected. I recommend explicitly adding permissions for workflow runs and checking if it helps:

permissions:
  contents: read
  pull-requests: write
  issues: write
  workflows: write

2. Use a Personal Access Token (PAT)

If you’re running this workflow in a forked repository or GitHub Actions environments where the default GITHUB_TOKEN might have limited permissions, using a PAT might be necessary. To generate a PAT:
	•	Go to your GitHub settings.
	•	Under “Developer Settings,” generate a new PAT with repo and workflow scopes.
	•	Store this token in your repository secrets, for example, under PAT_TOKEN.

Update your workflow to use the PAT:

with:
  github_token: ${{ secrets.PAT_TOKEN }}

3. Debugging Permissions Issues

GitHub’s 403 errors can be tricky. Here are some additional steps for debugging:
	•	Ensure that the workflow is triggered by an event that grants the correct permissions. In particular, PR events from forked repositories often lack write permissions for security reasons.
	•	You can add a debugging step in your workflow to output information about the GitHub token’s permissions:

      - name: Debug Token Permissions
        run: |
          echo "Checking token permissions..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}

This will allow you to understand whether the token has the correct permissions or is restricted.

Summary of Changes

	1.	Add explicit workflows: write permission to the job.
	2.	Try using a PAT instead of the default GITHUB_TOKEN if the repository is forked.
	3.	Debug the token’s permissions using a debugging step.

Here’s an updated version of your workflow incorporating these suggestions:

name: Auto generate PR Description [C4F]

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      workflows: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Token Permissions
        run: |
          echo "Checking token permissions..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}

      - name: Auto-generate PR Description
        uses: hqnicolas/auto-pr-description-g4f-action@v1.2.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: 'o1-mini'

Let me know if this helps solve the issue, or if you need more support in adjusting the permissions.

**Comment by hlohaus** [comment]
You need to do things like the copilot does to work properly.
https://github.com/xtekky/gpt4free/blob/main/.github%2Fworkflows%2Fcopilot.yml

**Comment by yuri-val** [comment]
@hlohaus what do you mean?

**Comment by hlohaus** [comment]
I'll update the pull request.

**Comment by yuri-val** [comment]
@hlohaus I don't see the point of doing this for several reasons:
- The PR description shouldn't depend on whether the tests have passed or not
- I will lose the context of the event

As a result:
- I will have to adapt the `workflow` specifically for your project
- If someone wants to use this `action`, they will have to adapt their `workflow` to this `action`

**Comment by hlohaus** [comment]
I will merge your PR, but you will see. 🙅‍♂️ You have not enoght permission for writing to the Pull Request 🙅‍♂️

**Comment by hlohaus** [comment]
https://github.com/xtekky/gpt4free/actions/runs/11881376591/job/33105637066

RuntimeError: Failed to fetch branches. Exit code: 32768

**Comment by yuri-val** [comment]
> https://github.com/xtekky/gpt4free/actions/runs/11881376591/job/33105637066
> 
> 
> 
> RuntimeError: Failed to fetch branches. Exit code: 32768

Ok, I'll check it tomorrow. 
"On my machine it works fine:)" ©️

**Pull request merged**
