### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skullcrushercmd**
your script for getting liaobots to work is outdated and ass

### CODE REVIEW

**Comment by skullcrushercmd** [comment]
unfinished but usable code in js, will need to convert it into python anyways so you can make whatever changes. 

every ip gets 4-5 authcodes which is ab 8k tokens, a cookie is needed and doesnt expire to get past bot auth and you can figure out the rest from the code
https://github.com/any-VM/anyVM-bot/blob/main/gpt.js

**Comment by hlohaus** [comment]
In my opinion, Liaobots is performing adequately and effectively. I do not perceive any immediate areas that require modification or improvement.

**Comment by skullcrushercmd** [comment]
> In my opinion, Liaobots is performing adequately and effectively. I do not perceive any immediate areas that require modification or improvement.

It doesn't check if it can get the auth codes and it only gets a single authcode, youre able to at least get 5 of them but even then the script can at least throw a meaningful error when you can't get anymore authcodes/ ran out of credits with a suggestion to use a VPN, also implementing a proxy connection could allow you to gather more authcodes, it's shouldn't be a matter if it works rather does it work well. If you really think that way no wonder so many of the providers doesn't work among other things.

**Comment by hlohaus** [comment]
If i use it sometimes, because the free 5 gpt-4 messages. It's totally perfect. Maybe we could add a note to the readme?

**Comment by skullcrushercmd** [comment]
also if you have discord id rather talk on there and maybe pick your brain on how g4f is structured overall because im making a js adaptation and it would help asking someone who works on it.

**Comment by skullcrushercmd** [comment]
also the script for you.com seems to be broken, specifically getting the telemetry id or smth

`Using You provider and gpt-4 model
No .har file found
Getting telemetry_id for you.com with nodriver
ERROR:root:
Traceback (most recent call last):
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\gui\server\api.py", line 174, in _create_response_stream
    for chunk in ChatCompletion.create(**kwargs):
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\providers\base_provider.py", line 216, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\providers\base_provider.py", line 45, in await_callback
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\Provider\You.py", line 79, in create_async_generator
    cookies = await cls.get_cookies(session) if chat_mode != "default" else None
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\Provider\You.py", line 159, in get_cookies
    cls._cookies = await cls.create_cookies(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\Provider\You.py", line 186, in create_cookies
    cls._telemetry_ids = await get_telemetry_ids()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooni\Documents\github\gpt4free\g4f\Provider\you\har_file.py", line 90, in get_telemetry_ids
    browser = await start()
              ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nodriver\core\util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nodriver\core\browser.py", line 87, in create
    await instance.start()
  File "C:\Python312\Lib\site-packages\nodriver\core\browser.py", line 312, in start
    await asyncio.create_subprocess_exec(
  File "C:\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 1742, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 523, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
127.0.0.1 - - [07/May/2024 17:52:10] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [07/May/2024 17:52:10] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
Closing port 8080
Closing port 8080`

**Comment by hlohaus** [comment]
Hey, it need either a nodriver or a .har file for You.com. The error messages are coming from nodriver, and it needs the original event loop. Did you change the event loop or are you using duckduckgo-search?

**Comment by hlohaus** [comment]
I updated the Liabots provider. Two types of authentication are now used.

**Pull request closed without merging**
