### PR TITLE
Update README.md + made a Jupyter notebook

### PR DESCRIPTION
**Pull request by DanielShemesh**
### Changes:
* I turned the table of contents into an actual table and added the new sections as well (docker, GUI, etc).
* I made a Colab notebook with a quora example usage
* I added a status column to specify which APIs are active or not

I didn't add the notebook file to the repo because I might change it constantly, but you can check it out [here](https://github.com/DanielShemesh/gpt4free-colab/blob/main/gpt4free.ipynb)

btw I noticed you already removed some of the APIs, but I still left them in the table of contents as "inactive", but you can remove those rows completely from the table I made

### CODE REVIEW

**Comment by themanthestanthegran** [comment]
yeah yeah yeah love it love it

**Comment by DanielShemesh** [comment]
Thanks 😁 glad to help

**Comment by xtekky** [comment]
@DanielShemesh looking for stars haha, will link your notebook, feel free to improve it and add more examples

**Review by xtekky — CHANGES_REQUESTED** [review]
remove ora.sh related stuff, and phind.com status is up (should be ?)

**Comment by DanielShemesh** [comment]
I updated it, now everything should be fine

**Comment by DanielShemesh** [comment]
> remove ora.sh related stuff, and phind.com status is up (should be ?)

DONE

**Comment by DanielShemesh** [comment]
I added the announcement as well (I support it as well)

**Comment by DanielShemesh** [comment]
now I'm really DONE

**Comment by DanielShemesh** [comment]
I'm done I just keep updating the star count

**Comment by looxlyk82** [comment]
Preparing bulk substrate for colonised grain bag

**Pull request merged**
